name: cm_common
description: A new Flutter package project.
version: 0.0.1
homepage: main.dart

publish_to: 'none' 
environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  flutter_screenutil: ^5.5.4
  flutter_intl: ^0.0.1
  intl_utils: ^2.8.1
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  flutter_svg: ^1.1.6
  rxdart: ^0.27.5
  uuid: ^3.0.6
  flutter_riverpod: ^2.1.3
  flutter_secure_storage: ^7.0.1
  freezed_result: ^1.0.3+1
  freezed_annotation: ^2.2.0
  font_awesome_flutter: ^10.3.0
  getwidget: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any
  freezed: any
  json_serializable: any
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/image/
    - assets/icon/
    - assets/
    - assets/images/
    - assets/icons/

  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
